services:
    lexik_maintenance.driver.factory:
        class: Awaresoft\MaintenanceBundle\Drivers\DriverFactory
        arguments:
            - "@lexik_maintenance.driver.database"
            - "@translator.default"
            - "%lexik_maintenance.driver%"
        calls:
            - [setContainer, ["@service_container"]]